In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import math
from sklearn.metrics import classification_report,confusion_matrix,r2_score

In [ ]:
data_Train=pd.read_csv('/content/drive/MyDrive/classification_train.csv')
data_Train = data_Train.drop(columns='Unnamed: 0') 
print(data_Train)

       label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0          8       0       0       0       0       0       0       0       0   
1          4       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          8       0       0       0       0       0       0       0       0   
4          2       0       0       0       0       1       0       3       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
29995      3       0       0       0       0       0       0       0       0   
29996      4       0       0       0       0       0       0       0       0   
29997      9       0       0       0       0       0       0       0       0   
29998      4       0       0       0       0       1       0       0       0   
29999      6       0       0       0       1       0       0       0       0   

       pixel9  ...  pixel775  pixel776 

In [ ]:
X = data_Train.drop(columns='label', axis=1)
print(X)

       pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0     130   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       1       0       3       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
29995       0       0       0       0       0       0       0       0      10   
29996       0       0       0       0       0       0       0       0       1   
29997       0       0       0       0       0       0       0       0       0   
29998       0       0       0       0       1       0       0       0       0   
29999       0       0       0       1       0       0       0       0       0   

       pixel10  ...  pixel7

In [ ]:
Y= data_Train["label"]
print(Y)

0        8
1        4
2        1
3        8
4        2
        ..
29995    3
29996    4
29997    9
29998    4
29999    6
Name: label, Length: 30000, dtype: int64


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test = train_test_split(X,Y,random_state=10, test_size=0.2, shuffle=True)

In [ ]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

       pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
4762        0       0       0       0       0       0       0       0       0   
26106       0       0       0       0       0       2       0      32      82   
16205       0       0       0       0       0       0       0       0       1   
26722       0       0       0       0       0       0       0       0       0   
12398       0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
28017       0       0       0       0       0       0       0       0       0   
17728       0       0       0       0       0       0       0       0       0   
29199       0       0       0       0       0       0       0       0       0   
7293        0       0       0       0       0       0       0       1       0   
17673       0       0       0       0       0       0       0       0       2   

       pixel10  ...  pixel7

In [ ]:
X_train=X_train.to_numpy()
X_test=X_test.to_numpy()
y_train=y_train.to_numpy()
y_test=y_test.to_numpy()

In [ ]:
class KNearestNieghbour:
   def __init__(self, no_of_neighbours, epsilon):
        self.k = no_of_neighbours
        self.epsilon = epsilon
        

   def train(self, x, y):
        self.X_Train = x
        self.Y_Train = y
         

   def predict_value(self, X_Test):
        distances = self.distance_matrix(X_Test)
        predicted_values=self.predict_label(distances)
        return predicted_values

     
   def distance_matrix(self, X_Test):
        X_Test_square = np.sum(X_Test ** 2, axis=1, keepdims=True)
        X_Train_square = np.sum(self.X_Train ** 2, axis=1, keepdims=True)
        X_Test_multiply_X_Train = np.dot(X_test, self.X_Train.T)
        return np.sqrt(self.epsilon + X_Test_square + X_Train_square.T- 2 * X_Test_multiply_X_Train)

   def predict_label(self, distances):
        number_test_cases = distances.shape[0]
        Y_predicted = np.zeros(number_test_cases)

        for i in range(number_test_cases):
            y_index = np.argsort(distances[i, :])
            K_Nearest_labels = self.Y_Train[y_index[: self.k]]       #.astype(int)
            Y_predicted[i] = np.argmax(np.bincount(K_Nearest_labels))

        return Y_predicted   
   def classification_materics(ypredict,ytest): 
     print(classification_report(ytest,ypredict))
     print(confusion_matrix(ytest,ypredict))     

In [ ]:
KNN=KNearestNieghbour(10,0)
KNN.train(X_train,y_train)
Y_labels=KNN.predict_value(X_test)

In [ ]:
print(classification_report(y_test,Y_labels))
print(confusion_matrix(y_test,Y_labels))


              precision    recall  f1-score   support

           0       0.75      0.91      0.82       590
           1       0.99      0.97      0.98       619
           2       0.72      0.75      0.74       627
           3       0.90      0.88      0.89       583
           4       0.76      0.74      0.75       590
           5       0.99      0.79      0.88       595
           6       0.65      0.56      0.60       632
           7       0.85      0.95      0.89       589
           8       0.97      0.94      0.96       593
           9       0.89      0.96      0.92       582

    accuracy                           0.84      6000
   macro avg       0.85      0.85      0.84      6000
weighted avg       0.85      0.84      0.84      6000

[[536   0  13   8   1   0  28   0   4   0]
 [  2 601   0  12   1   0   2   0   1   0]
 [  7   0 473   7  76   0  62   0   2   0]
 [ 23   6   3 512  22   0  17   0   0   0]
 [  5   0  65  15 439   0  64   0   2   0]
 [  1   0   1   2   0 469 