In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import math

In [ ]:
data_Train=pd.read_csv('/content/drive/MyDrive/classification_train.csv')
data_Train = data_Train.drop(columns='Unnamed: 0') 
print(data_Train)
data_Train_one_hot_encoded=pd.get_dummies(data_Train, columns=['label'])
print(data_Train_one_hot_encoded)
data_Train=data_Train.to_numpy()

       label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0          8       0       0       0       0       0       0       0       0   
1          4       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          8       0       0       0       0       0       0       0       0   
4          2       0       0       0       0       1       0       3       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
29995      3       0       0       0       0       0       0       0       0   
29996      4       0       0       0       0       0       0       0       0   
29997      9       0       0       0       0       0       0       0       0   
29998      4       0       0       0       0       1       0       0       0   
29999      6       0       0       0       1       0       0       0       0   

       pixel9  ...  pixel775  pixel776 

In [ ]:
def normalize_data(x):
 mu=np.mean(x,axis=0)
 sigma=np.std(x,axis=0)
 x=(x-mu)/sigma
 return x

In [ ]:
X_data=data_Train_one_hot_encoded.to_numpy()
X=X_data[:,0:784]
X=normalize_data(X)
m=X.shape[0]
print(m)
n=X.shape[1]
print(n)
print(X)
Y_label_data=X_data[:,784:794]
print(Y_label_data.shape)
print(Y_label_data)

30000
784
[[-0.01100826 -0.02635862 -0.03452104 ... -0.15842376 -0.09071855
  -0.03516399]
 [-0.01100826 -0.02635862 -0.03452104 ... -0.15842376 -0.09071855
  -0.03516399]
 [-0.01100826 -0.02635862 -0.03452104 ... -0.15842376 -0.09071855
  -0.03516399]
 ...
 [-0.01100826 -0.02635862 -0.03452104 ... -0.15842376 -0.09071855
  -0.03516399]
 [-0.01100826 -0.02635862 -0.03452104 ... -0.15842376 -0.09071855
  -0.03516399]
 [-0.01100826 -0.02635862 -0.03452104 ... -0.15842376 -0.09071855
  -0.03516399]]
(30000, 10)
[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
class LogisticRegression:
   def Train_data(x,y,learning_rate,no_of_iterations):
     #y 's shape = (30000,1)
     # x's shape =(30000,784)
    m=x.shape[0]#training
    n=x.shape[1]#features
    w=np.zeros((n,1))
    b= 0
    cost=[]
    for i in range(no_of_iterations):
      z=np.dot(x,w)+b#(30000,1)
      y_pred=1/(1 + np.exp(-z))
      cost_i = (-1/(m))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred),axis = 0)
      a= y_pred - y #(m,1)
      a1 = a.transpose()#(1,m)
      derivative_w=(1/m)*np.dot(a1,x)#(1,n)
      derivative_w_T=derivative_w.transpose()
      derivative_b=(1/m)*np.sum(y_pred-y,axis = 0,keepdims = True) # np.array([[1],[2],[3]])  python convert into np.array([1,2,3])
      w=w-(learning_rate)*(derivative_w_T)
      b=b-(learning_rate)*derivative_b
      cost.append(cost_i)
     
      if(i%math.ceil(no_of_iterations/100) == 0):
           print('Cost is:',cost_i,'after ',i,'iterations')
            # z_Test=np.dot(x,w)+b
            # Y_Test=1/(1 + np.exp(-z_Test))
            # plt.scatter( x[:,5], y, c='r', marker='x' )        
            # plt.plot(x[:,5], Y_Test , '-o')
            # plt.xlabel('X →')
            # plt.ylabel('Y →')
            # plt.show()
      
    return w,b,cost
   def predict_label(X_test,w,b):
     k=b.shape[0]
     m=X_test.shape[0]
     probability=np.zeros((10,m,1))
    #  wt=w.transpose()
     for i in range(k):
      #  wtk=w[k].transpose()
       z=np.dot(X_test,w[i])+b[i]
       y_pred=1/(1 + np.exp(-z))
       probability[i]=y_pred
    #  probability=np.delete(probability,0,axis=1) 
     final_results=(np.argmax(probability, axis=0))  
     return final_results




In [ ]:
learning_ratee_0=0.4
iterations_0=10000
Y_label_0=y_train[:,0].reshape(-1,1)
w_label_0,b_label_0,cost_label_0=LogisticRegression.Train_data(X_train,Y_label_0,learning_ratee_0,iterations_0)

Cost is: [0.69314718] after  0 iterations


<ipython-input-17-b2964a6a3462>:13: RuntimeWarning: divide by zero encountered in log
  cost_i = (-1/(m))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred),axis = 0)
<ipython-input-17-b2964a6a3462>:13: RuntimeWarning: invalid value encountered in multiply
  cost_i = (-1/(m))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred),axis = 0)


Cost is: [0.10102595] after  100 iterations
Cost is: [0.09443425] after  200 iterations
Cost is: [0.092394] after  300 iterations
Cost is: [0.0910673] after  400 iterations
Cost is: [0.090069] after  500 iterations
Cost is: [0.08926667] after  600 iterations
Cost is: [0.08859621] after  700 iterations
Cost is: [0.08802116] after  800 iterations
Cost is: [0.08751867] after  900 iterations
Cost is: [0.08707337] after  1000 iterations
Cost is: [0.08667441] after  1100 iterations
Cost is: [0.08631383] after  1200 iterations
Cost is: [0.08598557] after  1300 iterations
Cost is: [0.08568494] after  1400 iterations
Cost is: [0.08540818] after  1500 iterations
Cost is: [0.08515228] after  1600 iterations
Cost is: [0.08491473] after  1700 iterations
Cost is: [0.08469346] after  1800 iterations
Cost is: [0.08448672] after  1900 iterations
Cost is: [0.08429301] after  2000 iterations
Cost is: [0.08411105] after  2100 iterations
Cost is: [0.08393973] after  2200 iterations
Cost is: [0.08377809] af

In [ ]:
learning_ratee_1=1
iterations_1=5000
Y_label_1=y_train[:,1].reshape(-1,1)
w_label_1,b_label_1,cost_label_1=LogisticRegression.Train_data(X_train,Y_label_1,learning_ratee_1,iterations_1)

Cost is: [0.69314718] after  0 iterations


<ipython-input-17-b2964a6a3462>:13: RuntimeWarning: divide by zero encountered in log
  cost_i = (-1/(m))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred),axis = 0)
<ipython-input-17-b2964a6a3462>:13: RuntimeWarning: invalid value encountered in multiply
  cost_i = (-1/(m))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred),axis = 0)


Cost is: [nan] after  50 iterations
Cost is: [nan] after  100 iterations
Cost is: [nan] after  150 iterations
Cost is: [nan] after  200 iterations
Cost is: [nan] after  250 iterations
Cost is: [nan] after  300 iterations
Cost is: [nan] after  350 iterations
Cost is: [nan] after  400 iterations
Cost is: [nan] after  450 iterations
Cost is: [nan] after  500 iterations
Cost is: [nan] after  550 iterations
Cost is: [nan] after  600 iterations
Cost is: [nan] after  650 iterations
Cost is: [0.01558357] after  700 iterations
Cost is: [0.01461404] after  750 iterations
Cost is: [0.01383286] after  800 iterations
Cost is: [0.0132003] after  850 iterations
Cost is: [0.01268346] after  900 iterations
Cost is: [0.01225729] after  950 iterations
Cost is: [0.01190303] after  1000 iterations
Cost is: [0.01160632] after  1050 iterations
Cost is: [0.01135589] after  1100 iterations
Cost is: [0.01114269] after  1150 iterations
Cost is: [0.01095949] after  1200 iterations
Cost is: [0.01080045] after  125

In [ ]:
learning_ratee_2=0.2
iterations_2=2000
Y_label_2=y_train[:,2].reshape(-1,1)
w_label_2,b_label_2,cost_label_2=LogisticRegression.Train_data(X_train,Y_label_2,learning_ratee_2,iterations_2)

Cost is: [0.69314718] after  0 iterations
Cost is: [0.54665884] after  20 iterations
Cost is: [0.48232803] after  40 iterations
Cost is: [0.45911001] after  60 iterations
Cost is: [0.17396645] after  80 iterations
Cost is: [0.16440871] after  100 iterations
Cost is: [0.22671612] after  120 iterations
Cost is: [0.14603403] after  140 iterations
Cost is: [0.19125417] after  160 iterations
Cost is: [0.15576182] after  180 iterations
Cost is: [0.15474811] after  200 iterations
Cost is: [0.1864043] after  220 iterations
Cost is: [0.15622514] after  240 iterations
Cost is: [0.16988129] after  260 iterations
Cost is: [0.1583937] after  280 iterations
Cost is: [0.15946674] after  300 iterations
Cost is: [0.15725987] after  320 iterations
Cost is: [0.1550687] after  340 iterations
Cost is: [0.15406231] after  360 iterations
Cost is: [0.15241777] after  380 iterations
Cost is: [0.15117687] after  400 iterations
Cost is: [0.15001368] after  420 iterations
Cost is: [0.14887925] after  440 iteratio

In [ ]:
learning_ratee_3=0.5
iterations_3=1000
Y_label_3=y_train[:,3].reshape(-1,1)
w_label_3,b_label_3,cost_label_3=LogisticRegression.Train_data(X_train,Y_label_3,learning_ratee_3,iterations_3)

Cost is: [0.69314718] after  0 iterations


<ipython-input-17-b2964a6a3462>:13: RuntimeWarning: divide by zero encountered in log
  cost_i = (-1/(m))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred),axis = 0)
<ipython-input-17-b2964a6a3462>:13: RuntimeWarning: invalid value encountered in multiply
  cost_i = (-1/(m))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred),axis = 0)


Cost is: [3.90821007] after  10 iterations
Cost is: [nan] after  20 iterations
Cost is: [nan] after  30 iterations
Cost is: [1.46259488] after  40 iterations
Cost is: [0.16425712] after  50 iterations
Cost is: [0.1387141] after  60 iterations
Cost is: [0.12538564] after  70 iterations
Cost is: [0.11550782] after  80 iterations
Cost is: [0.10773925] after  90 iterations
Cost is: [0.10151388] after  100 iterations
Cost is: [0.09649941] after  110 iterations
Cost is: [0.09246678] after  120 iterations
Cost is: [0.08923832] after  130 iterations
Cost is: [0.08666534] after  140 iterations
Cost is: [0.08462017] after  150 iterations
Cost is: [0.08299398] after  160 iterations
Cost is: [0.08169599] after  170 iterations
Cost is: [0.08065229] after  180 iterations
Cost is: [0.0798041] after  190 iterations
Cost is: [0.07910565] after  200 iterations
Cost is: [0.07852183] after  210 iterations
Cost is: [0.07802603] after  220 iterations
Cost is: [0.07759827] after  230 iterations
Cost is: [0.0

In [ ]:
learning_ratee_4=0.1
iterations_4=1000
Y_label_4=y_train[:,4].reshape(-1,1)
w_label_4,b_label_4,cost_label_4=LogisticRegression.Train_data(X_train,Y_label_3,learning_ratee_3,iterations_3)

Cost is: [0.69314718] after  0 iterations


<ipython-input-17-b2964a6a3462>:13: RuntimeWarning: divide by zero encountered in log
  cost_i = (-1/(m))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred),axis = 0)
<ipython-input-17-b2964a6a3462>:13: RuntimeWarning: invalid value encountered in multiply
  cost_i = (-1/(m))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred),axis = 0)


Cost is: [3.90821007] after  10 iterations
Cost is: [nan] after  20 iterations
Cost is: [nan] after  30 iterations
Cost is: [1.46259488] after  40 iterations
Cost is: [0.16425712] after  50 iterations
Cost is: [0.1387141] after  60 iterations
Cost is: [0.12538564] after  70 iterations
Cost is: [0.11550782] after  80 iterations
Cost is: [0.10773925] after  90 iterations
Cost is: [0.10151388] after  100 iterations
Cost is: [0.09649941] after  110 iterations
Cost is: [0.09246678] after  120 iterations
Cost is: [0.08923832] after  130 iterations
Cost is: [0.08666534] after  140 iterations
Cost is: [0.08462017] after  150 iterations
Cost is: [0.08299398] after  160 iterations
Cost is: [0.08169599] after  170 iterations
Cost is: [0.08065229] after  180 iterations
Cost is: [0.0798041] after  190 iterations
Cost is: [0.07910565] after  200 iterations
Cost is: [0.07852183] after  210 iterations
Cost is: [0.07802603] after  220 iterations
Cost is: [0.07759827] after  230 iterations
Cost is: [0.0

In [ ]:
learning_ratee_5=0.3
iterations_5=1000
Y_label_5=y_train[:,5].reshape(-1,1)
w_label_5,b_label_5,cost_label_5=LogisticRegression.Train_data(X_train,Y_label_5,learning_ratee_5,iterations_5)

Cost is: [0.69314718] after  0 iterations


<ipython-input-17-b2964a6a3462>:13: RuntimeWarning: divide by zero encountered in log
  cost_i = (-1/(m))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred),axis = 0)
<ipython-input-17-b2964a6a3462>:13: RuntimeWarning: invalid value encountered in multiply
  cost_i = (-1/(m))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred),axis = 0)


Cost is: [1.09187764] after  10 iterations
Cost is: [1.56314362] after  20 iterations
Cost is: [0.25245427] after  30 iterations
Cost is: [0.58258983] after  40 iterations
Cost is: [0.48688446] after  50 iterations
Cost is: [0.47188547] after  60 iterations
Cost is: [0.13581066] after  70 iterations
Cost is: [0.08907922] after  80 iterations
Cost is: [0.08259881] after  90 iterations
Cost is: [0.07844571] after  100 iterations
Cost is: [0.07556048] after  110 iterations
Cost is: [0.07344548] after  120 iterations
Cost is: [0.07182095] after  130 iterations
Cost is: [0.07052149] after  140 iterations
Cost is: [0.06944552] after  150 iterations
Cost is: [0.06852848] after  160 iterations
Cost is: [0.06772831] after  170 iterations
Cost is: [0.06701985] after  180 iterations
Cost is: [0.06641041] after  190 iterations
Cost is: [0.06609621] after  200 iterations
Cost is: [0.06768932] after  210 iterations
Cost is: [0.08331578] after  220 iterations
Cost is: [0.16507725] after  230 iteratio

In [ ]:
learning_ratee_6=0.2
iterations_6=2000
Y_label_6=y_train[:,6].reshape(-1,1)
w_label_6,b_label_6,cost_label_6=LogisticRegression.Train_data(X_train,Y_label_6,learning_ratee_6,iterations_6)

Cost is: [0.69314718] after  0 iterations
Cost is: [1.37217515] after  20 iterations
Cost is: [1.05772856] after  40 iterations
Cost is: [0.86795604] after  60 iterations
Cost is: [0.26887283] after  80 iterations
Cost is: [0.19187078] after  100 iterations
Cost is: [0.34379967] after  120 iterations
Cost is: [0.20968024] after  140 iterations
Cost is: [0.24307857] after  160 iterations
Cost is: [0.23877233] after  180 iterations
Cost is: [0.23363396] after  200 iterations
Cost is: [0.22927694] after  220 iterations
Cost is: [0.22542953] after  240 iterations
Cost is: [0.22205573] after  260 iterations
Cost is: [0.21907989] after  280 iterations
Cost is: [0.21643895] after  300 iterations
Cost is: [0.21407995] after  320 iterations
Cost is: [0.21195932] after  340 iterations
Cost is: [0.21004134] after  360 iterations
Cost is: [0.20829669] after  380 iterations
Cost is: [0.2067012] after  400 iterations
Cost is: [0.20523487] after  420 iterations
Cost is: [0.20388104] after  440 iterat

In [ ]:
learning_ratee_7=0.3
iterations_7=2000
Y_label_7=y_train[:,7].reshape(-1,1)
w_label_7,b_label_7,cost_label_7=LogisticRegression.Train_data(X_train,Y_label_7,learning_ratee_7,iterations_7)

Cost is: [0.69314718] after  0 iterations


<ipython-input-17-b2964a6a3462>:13: RuntimeWarning: divide by zero encountered in log
  cost_i = (-1/(m))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred),axis = 0)
<ipython-input-17-b2964a6a3462>:13: RuntimeWarning: invalid value encountered in multiply
  cost_i = (-1/(m))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred),axis = 0)


Cost is: [0.68842835] after  20 iterations
Cost is: [0.23755941] after  40 iterations
Cost is: [0.08694721] after  60 iterations
Cost is: [0.07935438] after  80 iterations
Cost is: [0.08050498] after  100 iterations
Cost is: [0.08754742] after  120 iterations
Cost is: [0.07073615] after  140 iterations
Cost is: [0.0668467] after  160 iterations
Cost is: [0.06498053] after  180 iterations
Cost is: [0.06361457] after  200 iterations
Cost is: [0.06248799] after  220 iterations
Cost is: [0.06150421] after  240 iterations
Cost is: [0.0606225] after  260 iterations
Cost is: [0.0598225] after  280 iterations
Cost is: [0.05909081] after  300 iterations
Cost is: [0.0584174] after  320 iterations
Cost is: [0.05779442] after  340 iterations
Cost is: [0.05721552] after  360 iterations
Cost is: [0.05667552] after  380 iterations
Cost is: [0.05617008] after  400 iterations
Cost is: [0.05569556] after  420 iterations
Cost is: [0.05524883] after  440 iterations
Cost is: [0.05482721] after  460 iterati

In [ ]:
learning_ratee_8=0.1
iterations_8=1000
Y_label_8=y_train[:,8].reshape(-1,1)
w_label_8,b_label_8,cost_label_8=LogisticRegression.Train_data(X_train,Y_label_8,learning_ratee_8,iterations_8)

Cost is: [0.69314718] after  0 iterations
Cost is: [0.94544096] after  10 iterations


<ipython-input-17-b2964a6a3462>:13: RuntimeWarning: divide by zero encountered in log
  cost_i = (-1/(m))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred),axis = 0)
<ipython-input-17-b2964a6a3462>:13: RuntimeWarning: invalid value encountered in multiply
  cost_i = (-1/(m))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred),axis = 0)


Cost is: [0.55008314] after  20 iterations
Cost is: [nan] after  30 iterations
Cost is: [nan] after  40 iterations
Cost is: [nan] after  50 iterations
Cost is: [nan] after  60 iterations
Cost is: [nan] after  70 iterations
Cost is: [nan] after  80 iterations
Cost is: [nan] after  90 iterations
Cost is: [nan] after  100 iterations
Cost is: [nan] after  110 iterations
Cost is: [nan] after  120 iterations
Cost is: [nan] after  130 iterations
Cost is: [nan] after  140 iterations
Cost is: [nan] after  150 iterations
Cost is: [nan] after  160 iterations
Cost is: [nan] after  170 iterations
Cost is: [nan] after  180 iterations
Cost is: [nan] after  190 iterations
Cost is: [nan] after  200 iterations
Cost is: [nan] after  210 iterations
Cost is: [nan] after  220 iterations
Cost is: [nan] after  230 iterations
Cost is: [nan] after  240 iterations
Cost is: [nan] after  250 iterations
Cost is: [nan] after  260 iterations
Cost is: [nan] after  270 iterations
Cost is: [nan] after  280 iterations
Co

In [ ]:
learning_ratee_9=0.1
iterations_9=1000
Y_label_9=y_train[:,9].reshape(-1,1)
w_label_9,b_label_9,cost_label_9=LogisticRegression.Train_data(X_train,Y_label_9,learning_ratee_9,iterations_9)

Cost is: [0.69314718] after  0 iterations
Cost is: [0.67494208] after  10 iterations
Cost is: [0.43672269] after  20 iterations
Cost is: [0.33670014] after  30 iterations
Cost is: [0.2495966] after  40 iterations
Cost is: [0.19839953] after  50 iterations
Cost is: [0.17460269] after  60 iterations
Cost is: [0.16004796] after  70 iterations
Cost is: [0.1483333] after  80 iterations
Cost is: [0.13854339] after  90 iterations
Cost is: [0.13024955] after  100 iterations
Cost is: [0.1231417] after  110 iterations
Cost is: [0.11698872] after  120 iterations
Cost is: [0.11161481] after  130 iterations
Cost is: [0.10688408] after  140 iterations
Cost is: [0.10268989] after  150 iterations
Cost is: [0.09894749] after  160 iterations
Cost is: [0.09558877] after  170 iterations
Cost is: [0.0925584] after  180 iterations
Cost is: [0.089811] after  190 iterations
Cost is: [0.08730905] after  200 iterations
Cost is: [0.08502128] after  210 iterations
Cost is: [0.08292142] after  220 iterations
Cost 

In [ ]:
w_label_all=np.empty((10,784,1))
w_label_all[0]=w_label_0
w_label_all[1]=w_label_1
w_label_all[2]=w_label_2
w_label_all[3]=w_label_3
w_label_all[4]=w_label_4
w_label_all[5]=w_label_5
w_label_all[6]=w_label_6
w_label_all[7]=w_label_7
w_label_all[8]=w_label_8
w_label_all[9]=w_label_9
print(w_label_all.shape)
print(w_label_all[0].shape)
b_label_all=np.array([b_label_0,b_label_1,b_label_2,b_label_3,b_label_4,b_label_5,b_label_6,b_label_7,b_label_8,b_label_9]).reshape(-1,1)
print(b_label_all[0])

(10, 784, 1)
(784, 1)
[-7.4373356]


In [ ]:
finalresults=LogisticRegression.predict_label(X_test,w_label_all,b_label_all)
print(finalresults.shape)
print(y_test.shape)

(6000, 1)
(6000, 10)


In [ ]:
# from sklearn.metrics import classification_report,accuracy,confusion_matrix
# print(classification_report(finalresults,))

